export const environment = {
  production: true,
  BLUEPRINT_URL: 'https://widgets.risevision.com/staging/templates/PRODUCT_CODE/blueprint.json',
  canvaApiKey: '_Ow6FgJpQ3S_k0Mgyo1UX2nM',
  // AngularJS config
  APPS_ENV: 'PROD',
  CORE_URL: 'https://rvaserver2.appspot.com/_ah/api',
  STORE_ENDPOINT_URL: 'https://store-dot-rvaserver2.appspot.com/_ah/api',
  RVA_URL: 'http://rva.risevision.com',
  VIEWER_URL: 'https://widgets.risevision.com/viewer',
  SHARED_SCHEDULE_URL: 'https://widgets.risevision.com/viewer/?type=sharedschedule&id=SCHEDULE_ID',
  ALERTS_WS_URL: 'https://rvaserver2.appspot.com/alerts/cap',
  TAG_MANAGER_CONTAINER_ID: 'GTM-MMTK3JH',
  TAG_MANAGER_AUTH: null,
  TAG_MANAGER_ENV: null,
  STORAGE_ENDPOINT_URL: 'https://storage-dot-rvaserver2.appspot.com/_ah/api',
  MESSAGING_PRIMUS_URL: 'https://services.risevision.com/messaging/primus?displayId=apps&machineId=1',
  APPS_URL: '',
  ENV_NAME: 'BETA',
  OAUTH_TOKEN_PROVIDER_URL: 'https://services.risevision.com/oauthtokenprovider/',
  OAUTH_PUBLIC_KEY: 'EJMI-lB9hB55OYEsYmjXDNfRGoY',
  TWITTER_SERVICE_URL: 'https://services.risevision.com/twitter/',
  HUBSPOT_ACCOUNT: '2700250',
  HTML_TEMPLATE_URL: 'https://widgets.risevision.com/staging/templates/PRODUCT_CODE/src/template.html'
};
